### ISSUE TITLE
NavBar: When opening several times, things get messy

### ISSUE THREAD

**Issue by Azkali** [GerkinDev/e-make#18]
![deepin capture-ecran_zone de selection _20190114153014](https://user-images.githubusercontent.com/10491142/51118726-5d47ad80-1811-11e9-9c0c-a07b75556809.png)

# How to reproduce

Open and close Navbar several time.

**Comment by Azkali** [comment]
Seems to have resolved, maybe during an update of the app, closing until reproduced !

**Comment by GerkinDev** [comment]
If the issue is reproduced, please do some e2e, integration or unit testing to show up the failed assertion. Once a failed test case is revealed, the underlying bug will be super easy to fix.
